### ISSUE TITLE
APT

### ISSUE THREAD

**Issue by halkosajtarevic** [turnsk/gwtmvp#1]
Hi :) any plans to update the project to use annotation processors to be ready for GWT3?

**Comment by tomasbecket** [comment]
Hi, the quick answer would be "yes, sure!" Though I'm struggling to get decent information about GWT3 in general, let alone GWT3 APT. Should you have some detailed info, please do share it, I'm keen to get my hands dirty with it.

**Comment by halkosajtarevic** [comment]
Sorry for my late reply - didn't have access to a PC the last week.
You can take a look [here:](http://www.gwtcon.org/) Section "Slides" - the first Slides from @niloc321: Future of GWT 2.x
 For examples on APT-Generators you can take a look [here](https://github.com/intendia-oss/autorest)

**Comment by tomasbecket** [comment]
Not exactly detailed nor technical :( No offence to you, just letting the steam out over the lack of usable information over GWT3, yet alone documentation. Frustrating...

We'll probably wait until there's something we can comfortably work with. Should you feel like adding your two cents in the meantime, we'll be happy to accept a pull-request :)

**Comment by muksihs** [comment]
I understand that normal Java Annotation Code Generators will work just fine with GWT3, it does with GWT2, as their processing should occur before any transpiling is done.
